import type { Activity, Client, Project, Task } from "./types";
export const clients:Client[]=[
{id:"c1",name:"Amara Studio",company:"Amara Studio",industry:"Brand design",activeProjects:2,value:18400,tone:"Warm and concise"},{id:"c2",name:"Northstar Build",company:"Northstar Build Co.",industry:"Construction",activeProjects:1,value:12600,tone:"Direct and detailed"},{id:"c3",name:"Solace Health",company:"Solace Health",industry:"Healthcare",activeProjects:1,value:9800,tone:"Clear and reassuring"},{id:"c4",name:"Maji Coffee",company:"Maji Coffee Roasters",industry:"Hospitality",activeProjects:0,value:7200,tone:"Friendly and energetic"}];
export const projects:Project[]=[
{id:"p1",name:"Brand system refresh",clientId:"c1",status:"In progress",progress:68,due:"2026-09-24",budget:9400,color:"#166534"},{id:"p2",name:"Website launch",clientId:"c1",status:"Review",progress:86,due:"2026-09-18",budget:9000,color:"#0f766e"},{id:"p3",name:"Site operations portal",clientId:"c2",status:"In progress",progress:42,due:"2026-10-08",budget:12600,color:"#2563eb"},{id:"p4",name:"Patient onboarding",clientId:"c3",status:"Planning",progress:18,due:"2026-10-21",budget:9800,color:"#7c3aed"}];
export const initialTasks:Task[]=[
{id:"t1",title:"Approve responsive homepage",projectId:"p2",status:"Review",priority:"High",assignee:"Maya",due:"Sep 14"},{id:"t2",title:"Package icon library",projectId:"p1",status:"In progress",priority:"Medium",assignee:"Theo",due:"Sep 17"},{id:"t3",title:"Map contractor permissions",projectId:"p3",status:"Backlog",priority:"High",assignee:"Noah",due:"Sep 20"},{id:"t4",title:"Draft onboarding survey",projectId:"p4",status:"In progress",priority:"Medium",assignee:"Maya",due:"Sep 22"},{id:"t5",title:"Upload final brand assets",projectId:"p2",status:"Done",priority:"Low",assignee:"Theo",due:"Sep 12"},{id:"t6",title:"Review accessibility notes",projectId:"p1",status:"Review",priority:"High",assignee:"Maya",due:"Sep 13"},{id:"t7",title:"Set stakeholder workshop",projectId:"p4",status:"Backlog",priority:"Low",assignee:"Noah",due:"Sep 26"},{id:"t8",title:"QA invoice export",projectId:"p3",status:"Done",priority:"Medium",assignee:"Maya",due:"Sep 10"}];
export const activities:Activity[]=[
{id:"a1",actor:"Maya",action:"moved a task to Review",target:"Approve responsive homepage",time:"12 min ago",kind:"task"},{id:"a2",actor:"Theo",action:"uploaded",target:"brand-guidelines-v3.pdf",time:"44 min ago",kind:"file"},{id:"a3",actor:"Noah",action:"updated the deadline",target:"Site operations portal",time:"2 hr ago",kind:"project"},{id:"a4",actor:"Flow AI",action:"drafted a client update for",target:"Website launch",time:"3 hr ago",kind:"message"}];
export const revenue=[{month:"Apr",value:18},{month:"May",value:24},{month:"Jun",value:21},{month:"Jul",value:31},{month:"Aug",value:29},{month:"Sep",value:38}];
