import { describe,expect,it } from "vitest";
import { createDatabase,migrateTaskDueDates,seedDatabase } from ".";

describe("relational persistence",()=>{
 it("seeds linked workspace data",()=>{const db=createDatabase(":memory:");seedDatabase(db);expect((db.prepare("SELECT COUNT(*) n FROM clients WHERE workspace_id='w1'").get() as {n:number}).n).toBe(4);expect((db.prepare("SELECT COUNT(*) n FROM tasks t JOIN projects p ON p.id=t.project_id WHERE t.workspace_id=p.workspace_id").get() as {n:number}).n).toBe(8);db.close()});
 it("supports create, update, and delete in a transaction",()=>{const db=createDatabase(":memory:");seedDatabase(db);db.prepare("INSERT INTO tasks(id,workspace_id,project_id,title,status,priority,assignee,due) VALUES('test','w1','p1','Test task','Backlog','Low','Maya','2026-01-15')").run();db.prepare("UPDATE tasks SET status='Done' WHERE id='test'").run();expect((db.prepare("SELECT status FROM tasks WHERE id='test'").get() as {status:string}).status).toBe("Done");expect(db.prepare("DELETE FROM tasks WHERE id='test'").run().changes).toBe(1);db.close()});
 it("rejects cross-workspace foreign keys",()=>{const db=createDatabase(":memory:");seedDatabase(db);expect(()=>db.prepare("INSERT INTO projects(id,workspace_id,client_id,name,status,progress,due,budget,color) VALUES('bad','w-other','c1','Bad','Planning',0,'2026-01-01',0,'#166534')").run()).toThrow();db.close()});
 it("migrates legacy free-text task due dates to ISO calendar dates",()=>{const db=createDatabase(":memory:");seedDatabase(db);db.prepare("INSERT INTO tasks(id,workspace_id,project_id,title,status,priority,assignee,due) VALUES('a','w1','p1','A','Backlog','Low','Maya','Sep 14'),('b','w1','p1','B','Backlog','Low','Maya','Tomorrow'),('c','w1','p1','C','Backlog','Low','Maya','2026-09-20')").run();migrateTaskDueDates(db);const rows=db.prepare("SELECT id,due FROM tasks WHERE id IN ('a','b','c') ORDER BY id").all() as Array<{id:string;due:string}>;const iso=/^\d{4}-\d{2}-\d{2}$/;rows.forEach(r=>expect(r.due).toMatch(iso));expect(rows.find(r=>r.id==="c")!.due).toBe("2026-09-20");db.close()});
});
