"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Check, Sparkles, Zap } from "lucide-react";
import { Button, Card, Input } from "@/components/ui/primitives";

type Mode="login"|"signup"|"reset";
export default function LoginPage(){
 const router=useRouter();const [mode,setMode]=useState<Mode>("login");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [token,setToken]=useState("");const [resetDone,setResetDone]=useState(false);
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const form=new FormData(e.currentTarget);const body=Object.fromEntries(form);try{
  if(mode==="reset"){if(token){const r=await fetch("/api/auth/reset",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({token,password:body.password})});const data=await r.json();if(!r.ok)throw new Error(data.error);setResetDone(true);setToken("");return}const r=await fetch("/api/auth/reset",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:body.email})});const data=await r.json();if(!r.ok)throw new Error(data.error);setToken(data.developmentToken??"");return}
  const r=await fetch(`/api/auth/${mode}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error);router.push("/app");router.refresh();
 }catch(err){setError(err instanceof Error?err.message:"Something went wrong")}finally{setBusy(false)}};
 return <main className="grid min-h-screen lg:grid-cols-2"><section className="hidden bg-[#13251a] p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-3 font-bold"><span className="grid size-9 place-items-center rounded-xl bg-emerald-500"><Zap className="size-5" fill="currentColor"/></span>Alkebulan Flow</div><div className="max-w-lg"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-xs"><Sparkles className="size-3"/>AI Operations Hub</span><h1 className="mt-6 text-5xl font-bold leading-[1.05] tracking-tight">Run client work with clarity, not chaos.</h1><p className="mt-5 text-lg leading-8 text-emerald-50/70">Projects, tasks, files, and next actions—together in one calm workspace.</p><div className="mt-9 space-y-4 text-sm text-emerald-50/80">{["See every deadline before it becomes urgent","Turn project activity into client-ready updates","Give each teammate exactly the access they need"].map(x=><div key={x} className="flex items-center gap-3"><Check className="size-4 text-emerald-400"/>{x}</div>)}</div></div><p className="text-xs text-emerald-50/40">Local portfolio demo · no public contact details collected</p></section><section className="grid place-items-center p-5"><Card className="w-full max-w-md p-7 md:p-9"><div className="mb-7 flex items-center gap-3 font-bold lg:hidden"><span className="grid size-9 place-items-center rounded-xl bg-emerald-700 text-white"><Zap className="size-5"/></span>Alkebulan Flow</div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">{mode==="login"?"Welcome back":mode==="signup"?"Create workspace":"Development reset"}</p><h2 className="mt-2 text-3xl font-bold tracking-tight">{mode==="login"?"Sign in to your workspace":mode==="signup"?"Start your operations hub":token?"Choose a new password":"Reset your password"}</h2><p className="mt-2 text-sm text-muted-foreground">{mode==="reset"?"No email is sent locally. A one-time 15-minute token is shown only in development.":"Secure local access backed by hashed credentials and an HTTP-only session."}</p>
 <form className="mt-7 space-y-4" onSubmit={submit}>{mode==="signup"&&<><Field name="name" label="Your name" placeholder="Amina Tesfaye"/><Field name="workspaceName" label="Workspace name" placeholder="Acacia Studio"/></>} {mode!=="reset"||!token?<Field name="email" label="Workspace email" type="email" defaultValue={mode==="login"?"demo@alkebulan.local":""}/>:null} {mode!=="reset"||token?<Field name="password" label={mode==="reset"?"New password":"Password"} type="password" defaultValue={mode==="login"?"FlowDemo2026!":""}/>:null}{token&&<div className="rounded-xl bg-emerald-50 p-3 text-xs text-emerald-900"><b>Development token created.</b><br/><span className="break-all font-mono">{token}</span></div>}{resetDone&&<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">Password updated. Sign in with the new password.</p>}{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}<Button className="w-full" disabled={busy}>{busy?"Please wait…":mode==="login"?"Enter workspace":mode==="signup"?"Create workspace":token?"Update password":"Create reset token"}<ArrowRight className="size-4"/></Button></form>
 <div className="mt-6 flex justify-center gap-4 text-xs font-semibold"><button onClick={()=>{setMode(mode==="login"?"signup":"login");setError("");setToken("")}} className="text-emerald-700">{mode==="login"?"Create account":"Back to sign in"}</button>{mode!=="reset"&&<button onClick={()=>{setMode("reset");setError("")}} className="text-muted-foreground">Forgot password?</button>}</div><p className="mt-5 text-center text-[11px] leading-5 text-muted-foreground">Demo: demo@alkebulan.local · FlowDemo2026!<br/>Fictional, non-routable local credentials.</p></Card></section></main>
}
function Field({label,...props}:{label:string;name:string;type?:string;placeholder?:string;defaultValue?:string}){return <div><label className="mb-1.5 block text-xs font-bold" htmlFor={props.name}>{label}</label><Input id={props.name} required {...props}/></div>}
