import { randomUUID } from "node:crypto";
import { existsSync,unlinkSync } from "node:fs";
import { join } from "node:path";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { NextRequest } from "next/server";
import { getDatabase } from "@/lib/db";
import { hashPassword } from "@/lib/auth/password";
import { createSession,SESSION_COOKIE } from "@/lib/auth/session";
import { POST as createClient } from "./clients/route";
import { PATCH as updateClient,DELETE as deleteClient } from "./clients/[id]/route";
import { POST as createProject } from "./projects/route";
import { PATCH as updateProject,DELETE as deleteProject } from "./projects/[id]/route";
import { POST as createTask } from "./tasks/route";
import { PATCH as updateTask,DELETE as deleteTask } from "./tasks/[id]/route";
import { POST as uploadFile } from "./uploads/route";
import { POST as chat } from "./ai/chat/route";
import { POST as signup } from "./auth/signup/route";
import { POST as login } from "./auth/login/route";
import { POST as requestReset,PATCH as completeReset } from "./auth/reset/route";

const db=getDatabase();let ownerToken="",teamToken="",teamId="";const createdIds:string[]=[];const createdClients:string[]=[];const createdProjects:string[]=[];const uploadedIds:string[]=[];
function request(url:string,method:string,token:string,body?:unknown){return new NextRequest(url,{method,headers:{cookie:`${SESSION_COOKIE}=${token}`,...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined})}
beforeAll(()=>{ownerToken=createSession(db,"u1","w1").token;teamId=randomUUID();db.prepare("INSERT INTO users(id,name,email,password_hash) VALUES(?,?,?,?)").run(teamId,"Team Tester",`${teamId}@local.invalid`,hashPassword("TeamPassword123"));db.prepare("INSERT INTO memberships(user_id,workspace_id,role) VALUES(?,?,?)").run(teamId,"w1","team");teamToken=createSession(db,teamId,"w1").token});
afterAll(()=>{for(const id of createdIds)db.prepare("DELETE FROM tasks WHERE id=?").run(id);for(const id of createdProjects)db.prepare("DELETE FROM projects WHERE id=?").run(id);for(const id of createdClients)db.prepare("DELETE FROM clients WHERE id=?").run(id);for(const id of uploadedIds){const row=db.prepare("SELECT stored_name storedName FROM uploaded_files WHERE id=?").get(id) as {storedName:string}|undefined;if(row){const path=join(process.cwd(),"data","uploads",row.storedName);if(existsSync(path))unlinkSync(path);db.prepare("DELETE FROM uploaded_files WHERE id=?").run(id)}}db.prepare("DELETE FROM users WHERE id=?").run(teamId)});
describe("authenticated APIs",()=>{
 it("completes signup, login, and the safe development reset flow",async()=>{const suffix=randomUUID();const email=`${suffix}@local.invalid`;const password="InitialPass123";const signed=(await signup(new NextRequest("http://localhost/api/auth/signup",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:"Auth Tester",workspaceName:"Test Workspace",email,password})})))!;expect(signed.status).toBe(201);const logged=(await login(new NextRequest("http://localhost/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})})))!;expect(logged.status).toBe(200);const reset=(await requestReset(new NextRequest("http://localhost/api/auth/reset",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})})))!;const resetData=await reset.json();expect(resetData.developmentToken).toBeTruthy();const completed=(await completeReset(new NextRequest("http://localhost/api/auth/reset",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({token:resetData.developmentToken,password:"UpdatedPass456"})})))!;expect(completed.status).toBe(200);const user=db.prepare("SELECT id FROM users WHERE email=?").get(email) as {id:string};const membership=db.prepare("SELECT workspace_id workspaceId FROM memberships WHERE user_id=?").get(user.id) as {workspaceId:string};db.prepare("DELETE FROM users WHERE id=?").run(user.id);db.prepare("DELETE FROM workspaces WHERE id=?").run(membership.workspaceId)});
 it("protects the floating AI chat from anonymous requests",async()=>{const response=(await chat(new NextRequest("http://localhost/api/ai/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:"What is urgent?"})})))!;expect(response.status).toBe(401)});
 it("blocks team members from client management",async()=>{const response=(await createClient(request("http://localhost/api/clients","POST",teamToken,{name:"No",company:"No",industry:"",value:0,tone:""})))!;expect(response.status).toBe(403)});
 it("performs owner-authorized client CRUD",async()=>{const created=(await createClient(request("http://localhost/api/clients","POST",ownerToken,{name:"Test Client",company:"Test Client Co.",industry:"Testing",value:1000,tone:"Direct"})))!;expect(created.status).toBe(201);const client=await created.json();createdClients.push(client.id);const updated=(await updateClient(request(`http://localhost/api/clients/${client.id}`,"PATCH",ownerToken,{value:2000}),{params:Promise.resolve({id:client.id})}))!;expect((await updated.json()).value).toBe(2000);const deleted=(await deleteClient(request(`http://localhost/api/clients/${client.id}`,"DELETE",ownerToken),{params:Promise.resolve({id:client.id})}))!;expect(deleted.status).toBe(204);createdClients.splice(createdClients.indexOf(client.id),1)});
 it("performs owner-authorized project CRUD",async()=>{const created=(await createProject(request("http://localhost/api/projects","POST",ownerToken,{clientId:"c1",name:"API Project",status:"Planning",progress:0,due:"2026-12-01",budget:3000,color:"#166534"})))!;expect(created.status).toBe(201);const project=await created.json();createdProjects.push(project.id);const updated=(await updateProject(request(`http://localhost/api/projects/${project.id}`,"PATCH",ownerToken,{progress:25,status:"In progress"}),{params:Promise.resolve({id:project.id})}))!;const changed=await updated.json();expect(changed.progress).toBe(25);const deleted=(await deleteProject(request(`http://localhost/api/projects/${project.id}`,"DELETE",ownerToken),{params:Promise.resolve({id:project.id})}))!;expect(deleted.status).toBe(204);createdProjects.splice(createdProjects.indexOf(project.id),1)});
 it("validates, creates, updates, and deletes a persisted task",async()=>{const created=(await createTask(request("http://localhost/api/tasks","POST",ownerToken,{title:"API integration task",projectId:"p1",status:"Backlog",priority:"Medium",assignee:"Maya",due:"Tomorrow"})))!;expect(created.status).toBe(201);const task=await created.json();createdIds.push(task.id);const updated=(await updateTask(request(`http://localhost/api/tasks/${task.id}`,"PATCH",ownerToken,{status:"Done"}),{params:Promise.resolve({id:task.id})}))!;expect(updated.status).toBe(200);expect((await updated.json()).status).toBe("Done");const deleted=(await deleteTask(request(`http://localhost/api/tasks/${task.id}`,"DELETE",ownerToken),{params:Promise.resolve({id:task.id})}))!;expect(deleted.status).toBe(204);createdIds.splice(createdIds.indexOf(task.id),1)});
 it("rejects a mismatched upload before writing it",async()=>{const form=new FormData();form.set("file",new File(["not pdf"],"payload.exe",{type:"application/pdf"}));const req=new NextRequest("http://localhost/api/uploads",{method:"POST",headers:{cookie:`${SESSION_COOKIE}=${ownerToken}`},body:form});const response=(await uploadFile(req))!;expect(response.status).toBe(400);expect((await response.json()).error).toMatch(/mismatched/)})
 it("stores valid upload bytes and relational metadata",async()=>{const form=new FormData();form.set("file",new File(["name,status\nDemo,Ready"],"portfolio-test.csv",{type:"text/csv"}));form.set("projectId","p1");const req=new NextRequest("http://localhost/api/uploads",{method:"POST",headers:{cookie:`${SESSION_COOKIE}=${ownerToken}`},body:form});const response=(await uploadFile(req))!;expect(response.status).toBe(201);const data=await response.json();uploadedIds.push(data.id);const row=db.prepare("SELECT stored_name storedName,project_id projectId FROM uploaded_files WHERE id=?").get(data.id) as {storedName:string;projectId:string};expect(row.projectId).toBe("p1");expect(existsSync(join(process.cwd(),"data","uploads",row.storedName))).toBe(true)})
});
