"use client";
import { useState } from "react";
import { usePathname } from "next/navigation";
import { Bot,Send,Sparkles,X } from "lucide-react";
import { Button,Card,Input } from "@/components/ui/primitives";

type Message={role:"assistant"|"user";text:string};
export function FloatingChat(){const pathname=usePathname();const authenticated=pathname.startsWith("/app");const [open,setOpen]=useState(false);const [input,setInput]=useState("");const [busy,setBusy]=useState(false);const [messages,setMessages]=useState<Message[]>([{role:"assistant",text:authenticated?"Hi! I’m Flow AI. Ask me about project health, priorities, or client communication.":"Hi! I’m Flow AI. Sign in with the fictional demo account to ask questions about the workspace."}]);
 const append=(message:Message)=>setMessages(current=>[...current,message].slice(-12));
 const send=async(e:React.FormEvent)=>{e.preventDefault();const question=input.trim();if(!question||busy)return;const history=messages.slice(-8);append({role:"user",text:question});setInput("");if(!authenticated){append({role:"assistant",text:"Please sign in first so I can safely use workspace context."});return}setBusy(true);try{const response=await fetch("/api/ai/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:question,history})});const data=await response.json();append({role:"assistant",text:response.ok?data.reply:data.error??"I couldn’t answer that just now."})}catch{append({role:"assistant",text:"The assistant is temporarily unavailable."})}finally{setBusy(false)}};
 return <div className="fixed bottom-4 right-4 z-[60] sm:bottom-6 sm:right-6">{open&&<Card className="mb-3 flex h-[min(520px,70vh)] w-[min(370px,calc(100vw-2rem))] flex-col overflow-hidden shadow-2xl"><div className="flex items-center gap-3 border-b bg-[#17211b] p-4 text-white"><span className="grid size-9 place-items-center rounded-xl bg-emerald-500"><Sparkles className="size-4"/></span><div className="flex-1"><p className="text-sm font-bold">Flow AI</p><p className="text-[11px] text-emerald-100">{authenticated?"Workspace assistant":"Demo guide"}</p></div><button onClick={()=>setOpen(false)} aria-label="Close Flow AI"><X className="size-5"/></button></div><div className="flex-1 space-y-3 overflow-y-auto bg-[#f8faf7] p-4" aria-live="polite">{messages.map((m,i)=><div key={i} className={m.role==="user"?"ml-8 rounded-2xl rounded-br-sm bg-emerald-700 p-3 text-sm leading-5 text-white":"mr-6 rounded-2xl rounded-bl-sm border bg-white p-3 text-sm leading-5 text-slate-700"}>{m.text}</div>)}{busy&&<div className="mr-6 rounded-2xl border bg-white p-3 text-sm text-muted-foreground">Thinking…</div>}</div><form onSubmit={send} className="flex gap-2 border-t bg-white p-3"><Input value={input} onChange={e=>setInput(e.target.value)} maxLength={500} placeholder={authenticated?"Ask Flow AI…":"Ask about the demo…"} aria-label="Message Flow AI"/><Button className="px-3" aria-label="Send message" disabled={busy||!input.trim()}><Send className="size-4"/></Button></form></Card>}<button onClick={()=>setOpen(v=>!v)} className="ml-auto grid size-14 place-items-center rounded-full bg-[#17211b] text-white shadow-xl transition hover:scale-105 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700" aria-label={open?"Close Flow AI":"Open Flow AI chatbot"}><Bot className="size-6"/></button></div>}
