import { createHash,randomBytes } from "node:crypto";
import { NextRequest } from "next/server";
import { getDatabase } from "@/lib/db";
import { hashPassword } from "@/lib/auth/password";
import { sameOrigin } from "@/lib/auth/session";
import { emailSchema,passwordSchema } from "@/lib/validation";
import { z } from "zod";
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
export async function POST(request:NextRequest){if(!sameOrigin(request))return Response.json({error:"Invalid origin"},{status:403});const parsed=z.object({email:emailSchema}).safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({ok:true});const db=getDatabase();const user=db.prepare("SELECT id FROM users WHERE email=?").get(parsed.data.email) as {id:string}|undefined;let developmentToken:string|undefined;if(user){const token=randomBytes(24).toString("base64url");db.prepare("DELETE FROM password_reset_tokens WHERE user_id=? OR expires_at<=datetime('now')").run(user.id);db.prepare("INSERT INTO password_reset_tokens(token_hash,user_id,expires_at) VALUES(?,?,datetime('now','+15 minutes'))").run(hash(token),user.id);if(process.env.NODE_ENV!=="production")developmentToken=token}return Response.json({ok:true,message:"If the account exists, a reset token has been created.",developmentToken})}
export async function PATCH(request:NextRequest){if(!sameOrigin(request))return Response.json({error:"Invalid origin"},{status:403});const parsed=z.object({token:z.string().min(20),password:passwordSchema}).safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:parsed.error.issues[0]?.message??"Invalid input"},{status:400});const db=getDatabase();const record=db.prepare("SELECT user_id userId FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL AND expires_at>datetime('now')").get(hash(parsed.data.token)) as {userId:string}|undefined;if(!record)return Response.json({error:"Invalid or expired reset token"},{status:400});db.transaction(()=>{db.prepare("UPDATE users SET password_hash=? WHERE id=?").run(hashPassword(parsed.data.password),record.userId);db.prepare("UPDATE password_reset_tokens SET used_at=datetime('now') WHERE token_hash=?").run(hash(parsed.data.token));db.prepare("DELETE FROM sessions WHERE user_id=?").run(record.userId)})();return Response.json({ok:true})}
